maximum_name_length: 50
maximum_email_length: 255
minimum_password_length: 6
expired_time: 2
per_page: 5
per_page_category: 24
per_page_word: 100
gravatar_size: 50
words_number: 30
number_questions: 1
number_questions_validate_min: 2
number_questions_validate_max: 6
number_questions_validate_equal: 1
