maximum_name_length: 50
maximum_email_length: 255
minimum_password_length: 6
expired_time: 2
per_page: 5
per_page_category: 24
per_page_word: 100
gravatar_size: 50
words_number: 30
number_questions: 1
number_questions_validate_min: 2
number_questions_validate_max: 6
number_questions_validate_equal: 1
max_category_name_length: 50
max_image_size: 5
in_megabyte_number: 1024
stt_0: 0
stt_1: 1
per_page_category_admin: 5
per_page_word_admin: 30
default_locale: "en"
